### ISSUE TITLE
提建议：手机端连续加入图片功能

### ISSUE THREAD

**Issue by XiaoFuOS** [BeiYazi0/draw-card#3]
手机的话如果要图文一起发只能从最近的图片选择，如果是比较久远的图片，那就只能一张张发，可以考虑弄个指令，然后多少秒（分）内监听用户发送的图片，发一张就写入一张，这样用户可以在手机上发条指令，然后可以从久远的图库发图，但我不会写🤔

**Comment by BeiYazi0** [comment]
可以尝试以下思路
1.用一个字典记录各群是否处于洗入模式(T，F)及发起者
2.添加指令“开启洗入模式”，触发后修改该群状态为True，设定超时解除时间t，asyncio.sleep(t)阻塞结束后，发现没有退出洗入模式就强制退出并提醒用户。
3.添加指令“退出洗入模式”，触发后修改该群状态为False并提醒，若未处于洗入模式或结束用户非发起用户则提醒用户。
4.持续监听群消息，当该群处于洗入模式且满足黑白名单限制时，调用card_increase(str(ev.message),qqid)即可
